### PR TITLE
Fix incorrect CPP conditionals for GHC 8.0

### PR DESCRIPTION
**Pull request by DanielG**

### CODE REVIEW

**Comment by DanielG** [comment]
This issue is impacting ghc-mod users and blocking the ghc-mod-5.9 release, please consider merging and releasing it soon: https://github.com/DanielG/ghc-mod/issues/908

**Comment by nominolo** [comment]
Thanks. Merged and released as 0.2.3.3.

BTW, @DanielG would you (or someone else from the ghc-mod team) be interested in taking over maintainership of ghc-syb? It's basically just `ghc-syb-utils` and I noticed that the test suite actually fails for GHC 8.0+. I haven't used this in several years, and since ghc-mod seems to still be using it, it would probably be much better off in your hands.

**Comment by DanielG** [comment]
Sure thing. Just add me to the maintainers group on Hackage, my username there is also DanielG, and transfer the repo to me and I'll take over.

**Comment by nominolo** [comment]
Thanks. I added you to the maintainers on Hackage.
In order for transfer to work, you need to remove (or rename) your fork of `ghc-syb`.

**Comment by DanielG** [comment]
Done.

**Comment by DanielG** [comment]
*poke*

**Comment by nominolo** [comment]
It says it's in progress...

screen shot 2017-11-15 at 01 03 47

**Comment by DanielG** [comment]
Ah I did but it was so long ago it landed in my email archive. It says the transfer has expired tough, so can you just abort it and retry?

**Comment by nominolo** [comment]
OK, I re-did it. You probably have 24 hours to accept.

**Comment by DanielG** [comment]
Seems to have worked this time :)

**Comment by QuLogic** [comment]
If this fixed 8.0 support, then I suppose the README should maybe be updated?

**Comment by DanielG** [comment]
Honestly until I get around to setting up a CI system I'm not confident enough in any of the version bounds to boast about them ;)

**Pull request merged**
